# configuration
DEBUG = True
SECRET_KEY = '3sh2Emph&nK8bJwFFR'

# Database
DATABASE = 'lcbru_events'
SQLALCHEMY_DATABASE_URI = 'mysql://root:n0fwtj!@127.0.0.1/lcbru_events'
SQLALCHEMY_ECHO = True

RECAPTCHA_PUBLIC_KEY = '6LeRxQ4TAAAAAGHIo3USvQZHWzSe2wlhiBTqzqcK'
RECAPTCHA_PRIVATE_KEY = '6LeRxQ4TAAAAAAkuMvR02BrpYN0iPucHXRbgMQzq'